services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: meowchi
      POSTGRES_USER: meowchi
      POSTGRES_PASSWORD: meowchi
    ports: ["5432:5432"]
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    command: ["redis-server", "--save", "", "--appendonly", "no"]
  api:
    build: ./apps/api
    env_file:
      - ./apps/api/.env
    environment:
      DATABASE_URL: postgresql://meowchi:meowchi@db:5432/meowchi
      REDIS_URL: redis://redis:6379/0
    ports: ["8080:8080"]
    depends_on: [db, redis]
    develop:
      watch:
        - action: sync
          path: ./apps/api/src
          target: /app/src
        - action: rebuild
          path: ./apps/api/package.json
  web:
    build: ./apps/web
    ports: ["5173:5173"]
    develop:
      watch:
        - action: sync
          path: ./apps/web/src
          target: /app/src
        - action: rebuild
          path: ./apps/web/package.json

volumes:
  db-data:
