[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:both"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
