[build]
builder = "nixpacks"

[deploy]
startCommand = "node meowchi-admin-bot-v2/src/app.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = { default = "8080" }

[healthcheck]
path = "/health"
timeout = 60
interval = 30
