[build]
builder = "nixpacks"

[build.nixpacksConfig]
cwd = "meowchi-admin-bot-v2"

[deploy]
startCommand = "cd meowchi-admin-bot-v2 && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = { default = "8080" }

[healthcheck]
path = "/health"
timeout = 60
interval = 30
